application: fizerkhan
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /(.+)
  static_files: dist/\1
  upload: dist/(.*)

- url: /
  static_files: dist/index.html
  upload: dist/index.html

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^grunt\.js
- ^node_modules/(.*/)?
- ^posts/(.*/)?
- ^src/(.*/)?
- ^samples/(.*/)?
